<?php

class GeoIpRedirectController {
  protected static $instance = NULL;

  protected $languageSource = NULL;
  protected $originalCache = FALSE;

  public static function hook_boot() {
    if (php_sapi_name() === 'cli') { return; }

    $instance = new GeoIpRedirectController(
      $GLOBALS['base_url'],
      $_SERVER['HTTP_REFERER'],
      isset($_COOKIE['geoip_redirect'])
    );
    if ($instance->isActive()) {
      self::$instance = $instance;
    }
  }

  public static function hook_init() {
    if (isset(self::$instance)) {
      self::$instance->redirect(current_path());
      self::$instance->serveFromCache();
    };
  }

  public function __construct($base_url, $referer, $cookie) {
    $came_from_outside = substr($referer, 0, strlen($base_url)) != $base_url;
    if ($came_from_outside && !$cookie) {
      $this->languageSource = GeoIpRedirectMapping::fromDefaults();
      $this->setCookie();
      $this->deactivateCache();
    }
  }

  public function isActive() {
    return isset($this->languageSource);
  }

  protected function setCookie() {
    setcookie('geoip_redirect', '1', 0, $GLOBALS['base_path']);
  }

  protected function deactivateCache() {
    if ($this->originalCache = variable_get('cache')) {
      $GLOBALS['conf']['cache'] = FALSE;
    }
  }

  protected function serveFromCache() {
    if ($this->$originalCache) {
      $GLOBALS['conf']['cache'] = $this->originalCache;
      $cache = drupal_page_get_cache();
      if (is_object($cache)) {
        header('X-Drupal-Cache: HIT');
        drupal_serve_page_from_cache($cache);
        if (variable_get('page_cache_invoke_hooks', TRUE)) {
          bootstrap_invoke_all('exit');
        }
        // We are done.
        exit;
      }
    }
  }

  public function redirect($path) {
    $langCode = $this->languageSource->selectLanguage();
    _geoip_redirect_goto($langCode, $path);
  }

}

class GeoIpRedirectMapping {
  protected $path;
  protected $country;
  protected $links;
  protected $mapping;
  protected $defaultLanguage;
  protected $language;

  public static function fromDefaults() {
    // use @: see https://bugs.php.net/bug.php?id=59753
    $country = @geoip_country_code_by_name(ip_address());
    $mapping = variable_get('geoip_redirect_mapping', array());
    $language = language_default()->language;
    return new CountrySelectorRedirect($mapping, $country, $language);
  }
  
  public function selectLanguage(){
    $country = &$this->country;
    $_SESSION['geoip_redirect_country'] = $country;
    $mapping = &$this->mapping;
    if (isset($mapping[$country])) {
      return $mapping[$country];
    } else {
      return $this->defaultLanguage;
    }
  }

  public function __construct($mapping, $country, $default_language) {
    $this->mapping = $mapping;
    $this->country = $country;
    $this->defaultLanguage = $default_language;
  }
}

/**
 * Implements hook_boot().
 * 
 * Checks if we possibly want to redirect to another URL and
 * disables page-cache if so.
 */
function geoip_redirect_boot() {
  GeoIpRedirectController::hook_boot();
}

/**
 * Implements hook_init().
 * 
 * Do redirect if needed.
 */
function geoip_redirect_init() {
  GeoIpRedirectController::hook_init();
}

function _geoip_redirect_goto($lang, $path = NULL) {
  $path = isset($path) ? $path : current_path();
  $links = language_negotiation_get_switch_links('language', $path)->links;
  if (!isset($links[$lang]) || !isset($links[$lang]['href'])) {
    $lang = language_default()->language;
  }
  if (isset($links[$lang])) {
    $link = &$links[$lang];
    $path = isset($link['href']) ? $link['href'] : $path;
    drupal_goto($path, array('language' => $link['language']));
  }
}
