<?php

/**
 * Implements hook_menu().
 */
function geoip_language_redirect_menu() {
  $items['geoip-language-suggestions'] = [
    'page callback' => 'geoip_language_redirect_suggestions',
    'access callback' => TRUE,
  ];
  return $items;
}

/**
 * Page callback: Show language suggestions based on the IP.
 */
function geoip_language_redirect_suggestions() {
  $drupal = new \Drupal\geoip_language_redirect\Drupal();
  $header = $drupal->redirectHeader();
  if (isset($header['redirect']) && $header['redirect'] != 'no') {
    return [];
  }
  if (!isset($header['country']) || !($country = $header['country'])) {
    $country = $drupal->getCountry();
  }
  $mapping = $drupal->getMapping();
  $suggestions = [];
  if (isset($mapping[$country])) {
    $suggestions[] = $mapping[$country];
  }
  $suggestions[] = $drupal->defaultLanguage();

  drupal_json_output($suggestions);
  exit;
}

/**
 * Implements hook_preprocess_html().
 */
function geoip_language_redirect_preprocess_html(&$vars) {
  $drupal = new \Drupal\geoip_language_redirect\Drupal();
  $links = $drupal->translationLinks($drupal->currentPath());
  foreach ($links as $lang => $url) {
    drupal_add_html_head_link([
      'rel' => 'alternate',
      'hreflang' => $lang,
      'href' => $url,
    ]);
  }
}
